spring:
  application:
    name: CoinSec Service
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:xml/*Xml.xml

sa-token:
  token-name: ${TOKEN_NAME}
  timeout: 2592000
  active-timeout: 604800
  is-concurrent: true
  is-share: false
  token-style: uuid
